### ISSUE TITLE
Trying to integrate with botkit-storage-datastore

### ISSUE THREAD

**Issue by japtain-cack** [sebelga/nsql-cache-datastore#2] opened 2018-08-24 19:49 UTC
If you enable updated health checks in App Engine, it created redundant checks automatically. Our readyness check tests api functionality and during the process retrieves the OAuth keys from datastore. To reduce the number of reads I would like to integrate nsql-cache-datastore into botkit-storage-datastore. However, I'm not receiving any data after adding the nsql-cache-datastore code.

https://github.com/fabito/botkit-storage-datastore

modules/botkit-storage-datastore/src/index.js
```
var Datastore = require('@google-cloud/datastore');
const NsqlCache = require('nsql-cache');
const DatastoreAdapter = require('nsql-cache-datastore');

/**
 * The Botkit google cloud datastore driver
 *
 * @param {Object} config This must contain a `projectId` property
 * @returns {{teams: {get, save, all}, channels: {get, save, all}, users: {get, save, all}}}
 */
module.exports = function(config) {
    if (!config || !config.projectId) {
        throw new Error('projectId is required.');
    }

    var datastore = Datastore(config),
        namespace = config.namespace,
        teamKind = config.teamKind || 'BotkitTeam',
        channelKind = config.channelKind || 'BotkitChannel',
        userKind = config.userKind || 'BotkitUser';
    const db = DatastoreAdapter(datastore);
    const cache = new NsqlCache({ db });

    return {
        teams: {
            get: get(datastore, teamKind, namespace),
            save: save(datastore, teamKind, namespace),
            all: all(datastore, teamKind, namespace)
        },
        channels: {
            get: get(datastore, channelKind, namespace),
            save: save(datastore, channelKind, namespace),
            all: all(datastore, channelKind, namespace)
        },
        users: {
            get: get(datastore, userKind, namespace),

ETC.....
```

**Comment by loixlab** [comment] 2018-08-25 14:02
Hi,
Have you tried instantiating the datastore with `new` ?

```js
const datastore = new Datastore(config)
```
If this is not it, I'd need to see an example of the `get()` method to be able to reproduce the issue.
thanks!

**Comment by japtain-cack** [comment] 2018-08-27 17:49
I added `new`, but I'm still having the same issue. If I remove these two lines,
```
const db = DatastoreAdapter(datastore);
const cache = new NsqlCache({ db });
```
I'm able to hit datastore and get the requested data. However once I add them back in, it's a no go. I'm trying to check logging/debugging for something useful.

bot.js
```
 84 // Use datastore or mongo if specified, otherwise store in a JSON file local to the app.
 85 if(process.env.projectId && process.env.service){
 86   debug('Storage backend: datastore');
 87   datastoreStorage = require('botkit-storage-datastore')({
 88     "projectId": process.env.projectId,
 89     "namespace": process.env.service,
 90     "teamKind": process.env.service + "Team",
 91     "channelKind": process.env.service + "Channel",
 92     "userKind": process.env.service + "User"
 93   });
 94   bot_options.storage = datastoreStorage;
 95 } else if (process.env.MONGO_URI) {
 96   debug('Storage backend: mongo');
 97     var mongoStorage = require('botkit-storage-mongo')({mongoUri: process.env.MONGO_URI, tables: ['auth']});
 98     bot_options.storage = mongoStorage;
 99 } else {
100   debug('Storage backend: local');
101     bot_options.json_file_store = __dirname + '/.data/db/'; // store user data in a simple JSON format
102 }
```


jira-oauth.js
```
 93     // Used for readyness check to determine if API is responding
 94     test: function(request, response){
 95       getFromStorage('joauth')
 96       .then(data => {
 97         // Save OAuth data to memory to reduce storage queries
 98         controller.config.oauthAccessToken = data.oauthAccessToken;
 99         controller.config.oauthAccessTokenSecret = data.oauthAccessTokenSecret;
100
101         consumer.get(
102           process.env.jiraBaseUrl + "/rest/api/2/serverInfo",
103           data.oauthAccessToken || 'token',
104           data.oauthAccessTokenSecret || 'secret',
105           (err, data, resp) => {
106             if (err){
107               error('test: %s', err.data);
108               response.send('Jira API test failed: ' + err.data + '. Please try again');
109             }
110             else {
111               // If readyness checks are active this will spam your logs
112               //debug('JIRA API Test: %o', data);
113               response.send("Jira API data returned: " + data);
114             }
115           }
116         );
117       })
118       .catch(reason => {
119         error('test: %s', reason);
120         response.send("Storage lookup failed: " + reason);
121       });
122     }

153   function getFromStorage(id){
154     return new Promise((resolve, reject) => {
155       controller.storage.teams.get(id, (err, response) => {
156         if (err || !response){
157           reject('getFromStorage: Unable to read ' + id + ' data from storage: ' + err);
158         }
159         else{
160           resolve(response);
161         }
162       });
163     });
164   }

175   debug('Configured /joauth/test');
176   webserver.get('/joauth/test', handler.test);
```

botkit-storage-datastore/src/index.js
click [here](https://github.com/fabito/botkit-storage-datastore/blob/master/src/index.js) for the full module source.
```
  1 var Datastore = require('@google-cloud/datastore');
  2 const NsqlCache = require('nsql-cache');
  3 const DatastoreAdapter = require('nsql-cache-datastore');
  4
  5 /**
  6  * The Botkit google cloud datastore driver
  7  *
  8  * @param {Object} config This must contain a `projectId` property
  9  * @returns {{teams: {get, save, all}, channels: {get, save, all}, users: {get, save, all}}}
 10  */
 11 module.exports = function(config) {
 12     if (!config || !config.projectId) {
 13         throw new Error('projectId is required.');
 14     }
 15
 16     var datastore = new Datastore(config),
 17         namespace = config.namespace,
 18         teamKind = config.teamKind || 'BotkitTeam',
 19         channelKind = config.channelKind || 'BotkitChannel',
 20         userKind = config.userKind || 'BotkitUser';
 21     const db = DatastoreAdapter(datastore);
 22     const cache = new NsqlCache({ db });
 23
 24     return {
 25         teams: {
 26             get: get(datastore, teamKind, namespace),
 27             save: save(datastore, teamKind, namespace),
 28             all: all(datastore, teamKind, namespace)
 29         },
 30         channels: {
 31             get: get(datastore, channelKind, namespace),
 32             save: save(datastore, channelKind, namespace),
 33             all: all(datastore, channelKind, namespace)
 34         },
 35         users: {
 36             get: get(datastore, userKind, namespace),
 37             save: save(datastore, userKind, namespace),
 38             all: all(datastore, userKind, namespace)
 39         }

```

**Comment by loixlab** [comment] 2018-08-31 09:59
Hi,
Sorry for the late answer.. I am on holiday and not much time 😄 
I think I know why it is not working, it is because the datastore wrapped uses the Promise version of the Datastore API and you are using the callback one.

Can you try by modifying L57 of `botkit-storage-datastore/src/index.js` by

```js
datastore.get(key).then(function onSuccess(res) {
    const entity = res[0];
    return cb(null, entity ? entity : null);
}, function onError(err) {
    return cb(err);
});
```
Cheers

**Comment by loixlab** [comment] 2018-09-04 11:07
Hello,
Did you have the chance to try my last comment?
cheers :+1:

**Comment by japtain-cack** [comment] 2018-09-04 19:42
Sorry about the delay, and thanks for the reply. I've been out for the last few days. I'll try to get this tested as soon as possible. Might be a couple days though.

**Comment by loixlab** [comment] 2018-09-20 13:02
Hello,
I will close this issue for now, feel free to reopen if the problem persists after upgrading to the Promise api. I will add a note in the docs that the wrapped client is only using Promises
Cheers

**Closed as completed by loixlab** 2018-09-20 13:02 UTC
